/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package losayala.frames.registros;

import javax.swing.JInternalFrame;

/**
 *
 * @author ilichh1
 */
public class Contenedor extends javax.swing.JFrame {
    private static final RegistroAlbitro ARBITRO_FRAME = new RegistroAlbitro();
    private static final RegistroDT DIRECTOR_FRAME = new RegistroDT();
    private static final RegistroEquipo EQUIPO_FRAME = new RegistroEquipo();
    private static final RegistroGol GOL_FRAME = new RegistroGol();
    private static final RegistroJugador JUGADOR_FRAME = new RegistroJugador();
    private static final RegistroPartido PARTIDO_FRAME = new RegistroPartido();
    private static final RegistroUsuario USUARIO_FRAME = new RegistroUsuario();

    /**
     * Creates new form Contenedor
     */
    public Contenedor() {
        initComponents();
        
        JInternalFrame[] allFrames = new JInternalFrame[] {
            ARBITRO_FRAME,
            DIRECTOR_FRAME,
            EQUIPO_FRAME,
            GOL_FRAME,
            JUGADOR_FRAME,
            PARTIDO_FRAME,
            USUARIO_FRAME
        };
        
        addAllInternalFrames(allFrames);
        
        this.setVisible(true);
    }
    
    private void addAllInternalFrames(JInternalFrame[] frames) {
        for (JInternalFrame frame : frames) {
            addInternalFrame(frame);
        }
    }
    
    public void addInternalFrame(javax.swing.JInternalFrame internalFrame) {
        this.desktopPane.add(internalFrame);
        internalFrame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOS AYALA");
        setBounds(new java.awt.Rectangle(0, 23, 500, 500));

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));
        desktopPane.setBounds(new java.awt.Rectangle(0, 0, 500, 500));
        desktopPane.setLayout(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    // End of variables declaration//GEN-END:variables
}
