/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package losayala.frames.registros;

/**
 *
 * @author RENT A CENTER
 */
public class RegistroGol extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroGol
     */
    public RegistroGol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtbuscarJE = new javax.swing.JTextField();
        btnBuscarJE = new javax.swing.JButton();
        btnEliminarJE = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableJugadores = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SpinnerTiempo = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        ComboBoxJugadorGol = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Registro Goles");
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Buscar por Partido");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 102, 150, 19);
        getContentPane().add(txtbuscarJE);
        txtbuscarJE.setBounds(10, 130, 220, 20);

        btnBuscarJE.setText("Buscar");
        btnBuscarJE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarJEActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarJE);
        btnBuscarJE.setBounds(250, 130, 65, 23);

        btnEliminarJE.setText("Eliminar");
        getContentPane().add(btnEliminarJE);
        btnEliminarJE.setBounds(480, 130, 69, 23);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(142, 110, 410, 10);

        tableJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Partido", "Nombre", "Minuto "
            }
        ));
        jScrollPane2.setViewportView(tableJugadores);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 161, 540, 215);

        jButton8.setText("Guardar");
        getContentPane().add(jButton8);
        jButton8.setBounds(400, 130, 71, 23);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Gol");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 25, 19);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("Jugador:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 52, 16);
        getContentPane().add(SpinnerTiempo);
        SpinnerTiempo.setBounds(410, 70, 55, 20);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Minuto:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 70, 42, 16);

        getContentPane().add(ComboBoxJugadorGol);
        ComboBoxJugadorGol.setBounds(70, 70, 233, 20);

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 130, 61, 23);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Partido:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 40, 50, 16);

        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(70, 40, 460, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarJEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarJEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarJEActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxJugadorGol;
    private javax.swing.JSpinner SpinnerTiempo;
    private javax.swing.JButton btnBuscarJE;
    private javax.swing.JButton btnEliminarJE;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tableJugadores;
    private javax.swing.JTextField txtbuscarJE;
    // End of variables declaration//GEN-END:variables
}
